name: "Deploy API to staging server"
run-name: "Deploy API to staging server"
on:
  push:
    branches:
      - api
jobs:
  test:
    name: "Test API"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: api

      - name: Use Node.js 20.5.1
        uses: actions/setup-node@v1
        with:
          node-version: 20.5.1

      - name: cd into the api folder, install dependencies and run tests
        run: cd api && npm install && npm run test

  deploy:
    name: "Deploy API to staging server"
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Configure SSH
        run: |
          ls
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Pull the source
        run: ssh staging 'cd /home/ubuntu/Quentin-Desmettre-API && git restore . && git checkout api && git pull && cd api && npm install'

      - name: Restart the API
        run: ssh staging 'sudo systemctl restart quentin-desmettre-api'
