name: "Build WebSocket server and restart it"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: "Deploy API to staging server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          ls
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Pull & build the source
        run: ssh staging 'cd /home/ubuntu/Quentin-Desmettre/api && git checkout api && git pull && npm install'

      - name: Restart the API
        run: ssh staging 'sudo systemctl restart quentin-desmettre-api'
